version: '3.8'  

services:  
  backend:  
    build:  
      context: ./backend  
      dockerfile: Dockerfile  
    ports:  
      - '3000:3000'  
    environment:  
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/online_betting  
    depends_on:  
      postgres:
        condition: service_healthy

  frontend:  
    build:  
      context: ./frontend  
      dockerfile: Dockerfile  
    ports:  
      - '3001:4173'  
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:  
      - backend  

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=online_betting
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d online_betting']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: